/**
 * The synthetic-data invariants, as code (CNT-05).
 *
 * This module is deliberately the *other half* of the generators: every family
 * builds text here and every test checks it here, so "no real data" (AGENTS.md
 * rules 4 and 6, CNT-05's own warning, the `token-drill-generators` skill's safety
 * section) is a single reviewable list rather than a habit. It is exported because
 * the content pipeline (CNT-01) needs exactly these predicates to gate items before
 * publication - a generator that can only be validated from inside its own test
 * file cannot be used as a gate by the next person.
 *
 * The invariants, and why each one is the shape it is:
 *
 *  - IPv4 comes only from RFC 5737 TEST-NET-1/2/3 (`192.0.2.0/24`,
 *    `198.51.100.0/24`, `203.0.113.0/24`). Those /24s are reserved *by the IANA
 *    for documentation*, which means an address in them can never be assigned to a
 *    real host, so a drill can never point at somebody's server. RFC 1918 space
 *    (`10/8`, `172.16/12`, `192.168/16`) would be non-routable but still *look* like
 *    an internal network, and `127/8` would look like a loopback probe.
 *  - IPv6 comes only from RFC 3849's `2001:db8::/32`, the same idea.
 *  - UUIDs carry version nibble **8** (RFC 9562's "custom/experimental" version),
 *    not 4. A v4 UUID is 122 random bits and therefore indistinguishable from a
 *    real one; a v8-shaped UUID is still syntactically a UUID, is a shape no
 *    registry assigns, and cannot collide with a stored v4 value. The variant nibble
 *    stays in the RFC 4122 range (`8`, `9`, `a`, `b`) so a strict parser accepts it.
 *  - Hashes start with the fixed 16-hex marker `deadbeefcafebabe`. Real SHA output is
 *    indistinguishable from noise, so "obviously fake" has to be *structural*:
 *    every generated hash carries a human-legible prefix, which makes the value
 *    unmistakable to a reviewer and impossible to mistake for a digest of something
 *    real. Sixteen of 64 characters fixed also means a 48-bit prefix can never be
 *    reproduced by chance in the other direction.
 *  - ULIDs start with the fixed, readable marker `01SYNTHET1`. A ULID's first ten
 *    characters are a millisecond timestamp, so a real one encodes a date; fixing
 *    that prefix means no generated ULID encodes a plausible issuance time, and the
 *    letters `SYNTHETIC` are visible mid-string.
 *  - MAC addresses have the locally-administered bit (0x02) set and the multicast bit
 *    clear. The first octet can then only ever be one of eight values, none of which
 *    is a real vendor OUI.
 *  - Base64-shaped items are the encoding of `sample-<word>-<word>` - plain English
 *    that happens to be base64. The tell is that it decodes, which a secret does
 *    not usefully do.
 *  - Credential-shaped items start with `EXAMPLE-KEY` and never with a prefix any
 *    real provider uses (`sk-`, `AKIA`, `ghp_`, `AIza`, `xox?-`, a JWT header).
 *  - Dates come from a fixed window and never from the clock.
 */

/** RFC 5737 TEST-NET-1/2/3. The only IPv4 space this package may emit. */
export const DOC_IPV4_BLOCKS: readonly string[] = Object.freeze([
  "192.0.2.0/24",
  "198.51.100.0/24",
  "203.0.113.0/24",
]);

/**
 * The three /24s above as address prefixes. Kept separately because a generated address
 * is matched and generated by prefix, and deriving one from the other in two places is
 * how "192.0.2.0" and "192.0.2" drift apart.
 */
export const DOC_IPV4_PREFIXES: readonly string[] = Object.freeze(
  DOC_IPV4_BLOCKS.map((block) => block.split("/")[0]!.split(".").slice(0, 3).join(".")),
);

/** RFC 3849 documentation prefix. The only IPv6 space this package may emit. */
export const DOC_IPV6_PREFIX = "2001:db8::/32";

/** CIDRs offered as items: documentation networks only, fixed prefix lengths. */
export const SYNTHETIC_CIDRS: readonly string[] = Object.freeze([
  "192.0.2.0/24",
  "198.51.100.0/24",
  "203.0.113.0/24",
  "2001:db8::/32",
]);

/** Fixed opening of every generated hex hash. 16 of 40/64 characters. */
export const SYNTHETIC_HASH_MARKER = "deadbeefcafebabe";

/**
 * Fixed opening of every generated ULID: ten characters, the whole millisecond
 * timestamp field, so no generated ULID encodes a plausible issuance time and the
 * letters `SYNTHETIC` are visible mid-string.
 */
export const ULID_SYNTHETIC_PREFIX = "01SYNTHET1";

/** RFC 9562 version 8 ("custom"), which no registry assigns. Never 4. */
export const UUID_SYNTHETIC_VERSION = 8;

/** RFC 4122 variant nibbles, so a strict UUID parser still accepts the value. */
export const UUID_VARIANT_NIBBLES: readonly string[] = Object.freeze(["8", "9", "a", "b"]);

/**
 * First octets of a locally-administered unicast MAC: bit 0x02 set (locally
 * administered), bit 0x01 clear (not multicast). None is a real vendor OUI.
 */
export const LOCALLY_ADMINISTERED_MAC_OCTETS: readonly number[] = Object.freeze([
  0x02, 0x06, 0x0a, 0x0e, 0x12, 0x16, 0x1a, 0x1e,
]);

/** Port range: 1024 and up, so no generated port can name a privileged service. */
export const PORT_MIN = 1024;
export const PORT_MAX = 65535;

/**
 * The synthetic date window. Fixed, not "today minus N": a generator that reads
 * the clock is a generator whose stored drills silently change meaning.
 */
export const SYNTHETIC_DATE_MIN = "2001-01-01";
export const SYNTHETIC_DATE_MAX = "2035-12-31";

/** Plaintext every base64-shaped item decodes to. "A secret does not decode." */
export const BASE64_PLAINTEXT_PREFIX = "sample-";

/** Fixed opening of every credential-shaped string. */
export const CREDENTIAL_MARKER = "EXAMPLE-KEY";

/**
 * Prefixes real credentials use. A generated item matching any of these is a bug,
 * not a style choice, so {@link findSafetyViolations} fails on them.
 */
export const REAL_CREDENTIAL_PREFIXES: readonly string[] = Object.freeze([
  "sk-",
  "sk_live",
  "pk_live",
  "AKIA",
  "ASIA",
  "ghp_",
  "gho_",
  "ghs_",
  "github_pat_",
  "xoxb-",
  "xoxp-",
  "AIza",
  "ya29.",
  "eyJ",
]);

// ------------------------------------------------------------------- patterns

/**
 * Digit *ranges*, for embedding inside a character class. Written without the
 * brackets because `[${LOWER_HEX}]` would make a nested class (`[[0-9a-f]]`), which
 * matches a literal `[` and `]` as well as the digits - a silently wrong pattern.
 */
const LOWER_HEX_CLASS = "0-9a-f";

export const UUID_RE = new RegExp(
  `^[${LOWER_HEX_CLASS}]{8}-[${LOWER_HEX_CLASS}]{4}-${UUID_SYNTHETIC_VERSION}[${LOWER_HEX_CLASS}]{3}-[89ab][${LOWER_HEX_CLASS}]{3}-[${LOWER_HEX_CLASS}]{12}$`,
);
export const HASH_SHA1_RE = new RegExp(`^${SYNTHETIC_HASH_MARKER}[${LOWER_HEX_CLASS}]{24}$`);
export const HASH_SHA256_RE = new RegExp(`^${SYNTHETIC_HASH_MARKER}[${LOWER_HEX_CLASS}]{48}$`);
export const ULID_RE = new RegExp(
  `^${ULID_SYNTHETIC_PREFIX}[0123456789ABCDEFGHJKMNPQRSTVWXYZ]{16}$`,
);
export const BASE64ISH_RE = /^[A-Za-z0-9_-]{20,96}$/;
export const IPV4_RE = /^(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})$/;
export const CIDR_RE = /^([0-9.]+|\[[0-9a-f:]+\]|\S+?)\/(\d{1,3})$/;
export const MAC_RE = /^([0-9a-f]{2}:){5}[0-9a-f]{2}$/;
export const PORT_RE = /^\d{4,5}$/;
export const ISO_DATE_RE = /^\d{4}-\d{2}-\d{2}$/;
export const ISO_TIMESTAMP_RE = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d{3})?Z$/;
export const SEMVER_RE = /^\d{1,3}\.\d{1,3}\.\d{1,3}(-[0-9a-z.-]+)?(\+[0-9a-z.-]+)?$/;
export const CREDENTIAL_RE = /^EXAMPLE-KEY(-[A-Z0-9]{4}){4}$/;

const IPV4_IN_TEXT_RE = /\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b/g;
const EMAIL_RE = /[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}/g;
/**
 * IPv6 candidates inside arbitrary text. Only a run of hex groups and colons is
 * considered, and the boundary test below rejects anything glued to a letter or a
 * digit - without it, the `::` in a `namespace` identifier (`db::migrations`)
 * parses as a valid all-zero-prefix address and reports a false violation.
 */
const IPV6_CANDIDATE_RE = /[0-9a-fA-F]{0,4}(?::[0-9a-fA-F]{0,4}){2,}/g;

// --------------------------------------------------------------- IPv4 / IPv6

/** True only for an address inside an RFC 5737 documentation block. */
export function isDocumentationIPv4(value: string): boolean {
  const match = IPV4_RE.exec(value);
  if (match === null) return false;
  const octets = match.slice(1, 5).map(Number);
  if (octets.some((octet) => octet > 255)) return false;
  return DOC_IPV4_PREFIXES.includes(`${octets[0]}.${octets[1]}.${octets[2]}`);
}

/**
 * True only for an address in `2001:db8::/32`. Written against the *expanded* form
 * so a compressed address cannot hide behind its spelling.
 */
export function isDocumentationIPv6(value: string): boolean {
  const groups = expandIpv6(value);
  if (groups === null) return false;
  return groups[0] === "2001" && groups[1] === "db8";
}

/**
 * Expand an IPv6 address to its eight groups, or null when it is malformed.
 *
 * Implements the standard "::" rule: the longest run of two or more zero groups is
 * compressed, and on a tie the leftmost run wins (RFC 4291 2.2.2). Written by hand
 * rather than with `new URL('http://[::1]')` because this package must not depend on
 * the host's URL parser behaving identically.
 */
export function expandIpv6(value: string): string[] | null {
  const compressions = value.split("::").length - 1;
  if (compressions > 1) return null;
  const halves = value.split("::");
  const head = halves[0] === "" ? [] : halves[0]!.split(":");
  // With no `::` there is no second half at all, and `halves[1]` is undefined.
  const tail = compressions === 1 && halves[1] !== "" ? halves[1]!.split(":") : [];
  const present = [...head, ...tail];
  if (present.some((group) => group === "" || !/^[0-9a-fA-F]{1,4}$/.test(group))) return null;
  if (compressions === 0) return present.length === 8 ? present.map((g) => g.toLowerCase()) : null;
  if (present.length > 7) return null;
  const zeroes = Array.from({ length: 8 - present.length }, () => "0");
  return [...head.map((g) => g.toLowerCase()), ...zeroes, ...tail.map((g) => g.toLowerCase())];
}

// --------------------------------------------------------------------- MACs

export function isLocallyAdministeredMac(value: string): boolean {
  if (!MAC_RE.test(value)) return false;
  const first = Number.parseInt(value.slice(0, 2), 16);
  return LOCALLY_ADMINISTERED_MAC_OCTETS.includes(first);
}

// ---------------------------------------------------------------- base64ish

const BASE64URL_ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_";

/**
 * Encode ASCII bytes as unpadded base64url.
 *
 * Hand-written so the drill content does not depend on `Buffer` (absent in the
 * browser) or on `btoa` (which throws on any byte above 0x7f). The tests decode
 * these values with Node's own `Buffer.from(value, "base64url")`, so the two
 * implementations check each other.
 */
export function base64urlEncode(input: string): string {
  let out = "";
  for (let index = 0; index < input.length; index += 3) {
    const a = input.charCodeAt(index);
    const b = index + 1 < input.length ? input.charCodeAt(index + 1) : undefined;
    const c = index + 2 < input.length ? input.charCodeAt(index + 2) : undefined;
    out += BASE64URL_ALPHABET[a >> 2];
    out += BASE64URL_ALPHABET[((a & 0x03) << 4) | ((b ?? 0) >> 4)];
    if (b === undefined) break;
    out += BASE64URL_ALPHABET[((b & 0x0f) << 2) | ((c ?? 0) >> 6)];
    if (c === undefined) break;
    out += BASE64URL_ALPHABET[c & 0x3f];
  }
  return out;
}

/** Inverse of {@link base64urlEncode}; null when the input is not base64url. */
export function base64urlDecode(value: string): string | null {
  if (!BASE64ISH_RE.test(value)) return null;
  let bits = 0;
  let acc = 0;
  let out = "";
  for (const char of value) {
    const index = BASE64URL_ALPHABET.indexOf(char);
    if (index < 0) return null;
    acc = (acc << 6) | index;
    bits += 6;
    if (bits >= 8) {
      bits -= 8;
      out += String.fromCharCode((acc >> bits) & 0xff);
    }
  }
  return out;
}

/** True for a base64-shaped item whose plaintext is `sample-...`. */
export function isSyntheticBase64ish(value: string): boolean {
  if (!BASE64ISH_RE.test(value)) return false;
  const decoded = base64urlDecode(value);
  return decoded !== null && decoded.startsWith(BASE64_PLAINTEXT_PREFIX);
}

// ------------------------------------------------------------------ brackets

export interface BracketBalance {
  /** Net depth at the end. 0 for balanced text, +/-1 for an intentional imbalance. */
  readonly imbalance: number;
  /** Lowest depth reached; negative means a closer appeared with nothing open. */
  readonly minDepth: number;
  /** Deepest nesting reached, which is how a test proves the depth parameter held. */
  readonly maxDepth: number;
}

const BRACKET_PAIRS: Readonly<Record<string, string>> = Object.freeze({
  "(": ")",
  "[": "]",
  "{": "}",
  "<": ">",
});

/**
 * Walk the universal bracket set and report the depth trace. Counts all six
 * brackets from master-spec §7.1's `() [] {} <>`; the generators only emit brackets
 * their skin declares, so the universal count is the right one to assert on.
 */
export function bracketBalance(text: string): BracketBalance {
  const closers = new Set(Object.values(BRACKET_PAIRS));
  const stack: string[] = [];
  let depth = 0;
  let minDepth = 0;
  let maxDepth = 0;
  for (const char of text) {
    if (char in BRACKET_PAIRS) {
      stack.push(BRACKET_PAIRS[char]!);
      depth += 1;
      maxDepth = Math.max(maxDepth, depth);
    } else if (closers.has(char)) {
      depth -= 1;
      minDepth = Math.min(minDepth, depth);
    }
  }
  return { imbalance: depth, minDepth, maxDepth };
}

// ---------------------------------------------------------------- identifiers

const SNAKE = "^[a-z]+(_[a-z]+)*$";
const SCREAMING_SNAKE = "^[A-Z]+(_[A-Z]+)*$";
const KEBAB = "^[a-z]+(-[a-z]+)*$";
const DOT = "^[a-z]+(\\.[a-z]+)*$";
const NAMESPACE = "^[a-z]+(::[a-z]+)+$";
const IDENTIFIER_PATTERNS: Readonly<Record<string, RegExp>> = Object.freeze({
  snake: new RegExp(SNAKE),
  screaming_snake: new RegExp(SCREAMING_SNAKE),
  kebab: new RegExp(KEBAB),
  dot: new RegExp(DOT),
  namespace: new RegExp(NAMESPACE),
  camel: /^[a-z]+([A-Z][a-z0-9]*)+$/,
  pascal: /^[A-Z][a-z0-9]*([A-Z][a-z0-9]*)*$/,
});

/** True when `text` is a well-formed identifier in exactly one of the seven styles. */
export function isIdentifierInStyle(style: string, text: string): boolean {
  const pattern = IDENTIFIER_PATTERNS[style];
  return pattern !== undefined && pattern.test(text);
}

// ---------------------------------------------------------------- credentials

/**
 * True for the credential-shaped form: the marker is present, the shape is right,
 * and it does not begin like a credential any real provider issues.
 */
export function isSyntheticCredential(value: string): boolean {
  if (!CREDENTIAL_RE.test(value)) return false;
  return !REAL_CREDENTIAL_PREFIXES.some((prefix) => value.startsWith(prefix));
}

// ----------------------------------------------------------- global scan

export interface SafetyViolation {
  readonly kind: string;
  readonly detail: string;
}

/**
 * Scan arbitrary generated text for anything that could be mistaken for real data.
 *
 * Deliberately conservative: it reports a dotted-quad that is not documentation
 * space, an IPv6 literal outside `2001:db8::/32`, an email at a domain that is not
 * `example.{com,org,net}` (the domains the skill reserves for this purpose), and any
 * real credential prefix. A generator that fails this has either added a form
 * without a synthetic-data story or lost one of the markers.
 */
export function findSafetyViolations(text: string): SafetyViolation[] {
  const violations: SafetyViolation[] = [];
  for (const match of text.matchAll(IPV4_IN_TEXT_RE)) {
    if (!isDocumentationIPv4(match[0])) {
      violations.push({ kind: "ipv4-outside-documentation-space", detail: match[0] });
    }
  }
  for (const match of text.matchAll(IPV6_CANDIDATE_RE)) {
    const start = match.index ?? 0;
    const candidate = match[0];
    const before = start > 0 ? text[start - 1]! : "";
    const after = text[start + candidate.length] ?? "";
    if (/[A-Za-z0-9_]/.test(before) || /[A-Za-z0-9_]/.test(after)) continue;
    if (expandIpv6(candidate) !== null && !isDocumentationIPv6(candidate)) {
      violations.push({ kind: "ipv6-outside-documentation-space", detail: candidate });
    }
  }
  for (const match of text.matchAll(EMAIL_RE)) {
    const domain = match[0].split("@")[1] ?? "";
    if (!/^([a-z0-9-]+\.)*example\.(com|org|net)$/i.test(domain)) {
      violations.push({ kind: "email-outside-example-domain", detail: match[0] });
    }
  }
  for (const prefix of REAL_CREDENTIAL_PREFIXES) {
    if (text.includes(prefix)) {
      violations.push({ kind: "real-credential-prefix", detail: prefix });
    }
  }
  return violations;
}
