/**
 * The identifier vocabulary (CNT-05 `naming` family).
 *
 * LICENSING (AGENTS.md rule 6, CNT-07): every word below was written for this
 * file. No word list is copied from any source, and in particular nothing here
 * comes from Monkeytype or Keybr, whose word lists are GPL/AGPL and therefore
 * unusable. These are single common English words plus long-established computing
 * terms, and the file has no upstream provenance to attribute because it has no
 * upstream.
 *
 * WHY THESE WORDS AND NOT `user`, `name`, `item`:
 *
 *  1. `user`, `name`, `email`, `password`, `secret` are the words a naming drill
 *     most obviously wants, and they are exactly the ones that make generated
 *     identifiers look like records of real people. This list deliberately omits
 *     them: an identifier like `owner_email` is harmless, but a drill corpus full
 *     of `user_password` strings trains the eye to skim past the shape of a
 *     credential, which is the opposite of what this product teaches.
 *  2. Identifiers are built from *domain* words (queue, session, digest, stride)
 *     so that a mixed-convention listing reads like code instead of like a
 *     word-typing test. That is the whole point of Tier 6.
 *
 * WORD SHAPE is constrained by the tests: lowercase ASCII letters only, 3-14
 * characters, no digits, no spaces, no duplicates. That keeps every style's
 * rendering rule (capitalise, upper-case, join) the only transformation applied,
 * so a style conversion is unambiguous and PRG-14's inverse parse cannot be
 * ambiguous either.
 */

export const TECH_WORDS: readonly string[] = Object.freeze([
  // Nouns: data and plumbing
  "buffer",
  "cache",
  "cursor",
  "digest",
  "envelope",
  "header",
  "offset",
  "payload",
  "record",
  "schema",
  "segment",
  "shard",
  "signal",
  "sink",
  "span",
  "stream",
  "trailer",
  "window",
  "packet",
  "frame",
  "channel",
  "journal",
  "manifest",
  "registry",
  "catalog",
  "replica",
  "checksum",
  "snapshot",
  "cluster",
  "index",
  // Nouns: mechanisms
  "adapter",
  "allocator",
  "bridge",
  "broker",
  "bucket",
  "bundle",
  "codec",
  "collector",
  "connector",
  "container",
  "context",
  "converter",
  "dispatcher",
  "driver",
  "encoder",
  "gateway",
  "handler",
  "kernel",
  "launcher",
  "limiter",
  "linker",
  "loader",
  "logger",
  "mapper",
  "marker",
  "matcher",
  "mediator",
  "migrator",
  "mixer",
  "model",
  "module",
  "monitor",
  "observer",
  "operator",
  "optimizer",
  "parser",
  "partitioner",
  "planner",
  "plugin",
  "pointer",
  "pool",
  "port",
  "printer",
  "profiler",
  "projector",
  "provider",
  "proxy",
  "quantile",
  "reader",
  "recorder",
  "reducer",
  "relay",
  "renderer",
  "resolver",
  "retainer",
  "router",
  "sampler",
  "scanner",
  "scheduler",
  "selector",
  "sequencer",
  "serializer",
  "service",
  "sidecar",
  "splitter",
  "stack",
  "staging",
  "stub",
  "supervisor",
  "symbol",
  "table",
  "target",
  "template",
  "tenant",
  "tensor",
  "terminal",
  "thread",
  "ticker",
  "tokenizer",
  "tracker",
  "tracer",
  "transformer",
  "translator",
  "trigger",
  "tunnel",
  "validator",
  "vector",
  "verifier",
  "viewer",
  "watcher",
  "worker",
  "wrapper",
  "writer",
  // Nouns: metrics and states
  "counter",
  "gauge",
  "histogram",
  "margin",
  "metric",
  "quota",
  "ratio",
  "sample",
  "score",
  "threshold",
  "budget",
  "interval",
  "duration",
  "latency",
  "epoch",
  // Verbs
  "apply",
  "cancel",
  "clamp",
  "compact",
  "decode",
  "derive",
  "drain",
  "encode",
  "escape",
  "expand",
  "extract",
  "filter",
  "flush",
  "hydrate",
  "merge",
  "normalize",
  "parse",
  "publish",
  "reduce",
  "render",
  "resolve",
  "resume",
  "retry",
  "serialize",
  "split",
  "subscribe",
  "throttle",
  "unwrap",
  "validate",
  "verify",
  "wrap",
]);

/**
 * Words a generated string literal may contain: a subset of the vocabulary, so a
 * string drill and a naming drill share one voice, and short enough that a string
 * literal stays one line.
 */
export const STRING_WORDS: readonly string[] = Object.freeze([
  "buffer",
  "cursor",
  "digest",
  "segment",
  "session",
  "shard",
  "signal",
  "stream",
  "window",
  "payload",
  "retry",
  "timeout",
  "queued",
  "ready",
  "stale",
  "unknown",
]);
