import { describe, expect, it } from "vitest";

import { keyDown, keyUp, withKeyups } from "../fixtures/helpers.js";
import { computeResult } from "../src/index.js";
import { framesForLog } from "../src/replay.js";

import * as a01 from "../fixtures/a01.js";
import * as b01 from "../fixtures/b01.js";
import * as c01 from "../fixtures/c01.js";
import * as d01 from "../fixtures/d01.js";
import * as d02 from "../fixtures/d02.js";
import * as d03 from "../fixtures/d03.js";
import * as d04 from "../fixtures/d04.js";
import * as e01 from "../fixtures/e01.js";
import * as e02 from "../fixtures/e02.js";
import * as e03 from "../fixtures/e03.js";
import * as eCaps from "../fixtures/e-caps.js";
import * as eDeadkey from "../fixtures/e-deadkey.js";
import * as eEmoji from "../fixtures/e-emoji.js";
import * as eDualkey from "../fixtures/e-dualkey.js";
import * as f01 from "../fixtures/f01.js";
import * as g01 from "../fixtures/g01.js";

/**
 * Deterministic replay (ENG-08, implementation guide M1-10).
 *
 * The replay folds filterEvents → textAffecting → applyPress prefixes with
 * deriveCharStates per frame, plus keys-down, error indices and a timestamp.
 * Speed is a display concern (time scale only) and lives in the viewer, not
 * here. Every expectation below is hand-computed from the event list beside
 * it — no expectation is generated by the code under test.
 */

describe("framesForLog — deterministic replay (ENG-08)", () => {
  it("yields a single empty initial frame for an empty log", () => {
    const replay = framesForLog("hi", [], "free");
    expect(replay.frames).toHaveLength(1);
    expect(replay.frames[0]).toEqual({
      t: 0,
      text: "",
      states: ["untyped", "untyped"],
      caret: 0,
      keysDown: [],
      errorIndices: [],
      errorCount: 0,
    });
    expect(replay.finalText).toBe("");
    expect(replay.corrupted).toBe(false);
    expect(replay.errorCount).toBe(0);
  });

  it("folds one press into initial + one frame with the painted state", () => {
    // "h" at t=120 against "hi": buffer ["h"], both positions decided, the
    // caret sits after the produced character.
    const events = withKeyups([keyDown("h", 120)]);
    const replay = framesForLog("hi", events, "free");
    expect(replay.frames).toHaveLength(2);
    expect(replay.frames[1]).toEqual({
      t: 120,
      text: "h",
      states: ["correct", "missed"],
      caret: 1,
      keysDown: ["KeyH"],
      errorIndices: [],
      errorCount: 0,
    });
    expect(replay.finalText).toBe("h");
  });

  it("marks a wrong character incorrect with its error index", () => {
    // "x" against "a" in free mode: the press is kept and visible, so the
    // frame paints position 0 incorrect and reports it.
    const events = withKeyups([keyDown("x", 50)]);
    const replay = framesForLog("a", events, "free");
    expect(replay.frames[1]).toEqual({
      t: 50,
      text: "x",
      states: ["incorrect"],
      caret: 1,
      keysDown: ["KeyX"],
      errorIndices: [0],
      errorCount: 1,
    });
    expect(replay.errorCount).toBe(1);
  });

  it("replays a backspace-heavy prefix step by step", () => {
    // "a", "b", Backspace, "c" against "ac": four frames after the initial,
    // ending on the corrected text with no errors.
    const events = withKeyups([
      keyDown("a", 0),
      keyDown("b", 100),
      keyDown("Backspace", 200),
      keyDown("c", 300),
    ]);
    const replay = framesForLog("ac", events, "free");
    expect(replay.frames.map((f) => f.text)).toEqual(["", "a", "ab", "a", "ac"]);
    expect(replay.frames.map((f) => f.caret)).toEqual([0, 1, 2, 1, 2]);
    expect(replay.frames[2]!.states).toEqual(["correct", "incorrect"]);
    expect(replay.frames[2]!.errorIndices).toEqual([1]);
    expect(replay.frames[4]!.states).toEqual(["correct", "correct"]);
    expect(replay.finalText).toBe("ac");
    expect(replay.corrupted).toBe(false);
  });

  it("keeps intermediate frames untyped and finishes the last one", () => {
    // "h" then "i" against "hi": the middle frame must not call the
    // not-yet-reached position missed — that is only knowable at the end.
    const events = withKeyups([keyDown("h", 0), keyDown("i", 150)]);
    const replay = framesForLog("hi", events, "free");
    expect(replay.frames[1]!.states).toEqual(["correct", "untyped"]);
    expect(replay.frames[2]!.states).toEqual(["correct", "correct"]);
  });

  it("reports the keys held at each frame by code", () => {
    // Shift down at 0, "a" at 100, Shift up at 200: the middle frame sees the
    // modifier held, the initial and final frames do not.
    const events = [
      keyDown("Shift", 0, { code: "ShiftLeft" }),
      keyDown("a", 100),
      keyUp("a", 140),
      keyUp("Shift", 200, { code: "ShiftLeft" }),
    ];
    const replay = framesForLog("a", events, "free");
    // Only the printable "a" is text-affecting, so there is one frame past
    // the initial — and both it and the held Shift are down when it lands.
    expect(replay.frames).toHaveLength(2);
    expect(replay.frames[1]!.keysDown).toEqual(["KeyA", "ShiftLeft"]);
  });

  it("marks the log corrupted when the final text does not match the expectation", () => {
    const events = withKeyups([keyDown("h", 0), keyDown("i", 100)]);
    const matching = framesForLog("hi", events, "free", { expectedFinalText: "hi" });
    expect(matching.corrupted).toBe(false);
    // The buffer folds to "hi" but the finished attempt claims "ho": the
    // replay must say so rather than silently showing a wrong session.
    const mismatched = framesForLog("hi", events, "free", { expectedFinalText: "ho" });
    expect(mismatched.finalText).toBe("hi");
    expect(mismatched.corrupted).toBe(true);
  });

  it("marks out-of-order text-affecting timestamps as corrupted, never crashing", () => {
    // Built by hand, not with withKeyups: that helper sorts by time, which
    // would repair the very disorder this test is about.
    const events = [keyDown("b", 300), keyDown("a", 100), keyUp("b", 340), keyUp("a", 140)];
    const replay = framesForLog("ab", events, "free");
    expect(replay.corrupted).toBe(true);
    // The fold still runs in capture order — corruption is reported, not thrown.
    expect(replay.finalText).toBe("ba");
  });

  it("ignores non-scoring input in the fold but keeps it for keys-down", () => {
    // A repeat press and a modifier keydown change nothing about the text.
    const events = [
      keyDown("h", 0),
      keyDown("h", 60, { repeat: true }),
      keyDown("Shift", 80, { code: "ShiftLeft" }),
      keyUp("h", 100),
      keyDown("i", 120),
      keyUp("i", 160),
      keyUp("Shift", 180, { code: "ShiftLeft" }),
    ];
    const replay = framesForLog("hi", events, "free");
    expect(replay.frames.map((f) => f.text)).toEqual(["", "h", "hi"]);
    expect(replay.finalText).toBe("hi");
    expect(replay.corrupted).toBe(false);
  });
});

describe("framesForLog — every chapter fixture replays to its scored text (M1-10 check)", () => {
  // The replay must reproduce the exact final text the scorer computed, for
  // every fixture in the corpus — not just the tiny hand logs above. The
  // expectation is cross-consistency between the two engine paths (fold vs
  // computeResult), which is exactly what the M1-10 check demands; no new
  // numbers are asserted here, so there is nothing to hand-compute.
  const MODULES = [
    a01,
    b01,
    c01,
    d01,
    d02,
    d03,
    d04,
    e01,
    e02,
    e03,
    eCaps,
    eDeadkey,
    eEmoji,
    f01,
    g01,
  ];
  for (const mod of MODULES) {
    it(`${mod.FIXTURE_ID} replays to the exact scored final text`, () => {
      const expected = computeResult(mod.log, mod.text).finalText;
      const replay = framesForLog(mod.text.text, mod.log.events, mod.log.meta.settings.errorMode, {
        expectedFinalText: expected,
      });
      expect(replay.finalText).toBe(expected);
      expect(replay.corrupted).toBe(false);
    });
  }

  it("e-dualkey alt log replays to its own scored text", () => {
    const expected = computeResult(eDualkey.logAlt, eDualkey.textAlt).finalText;
    const replay = framesForLog(
      eDualkey.textAlt.text,
      eDualkey.logAlt.events,
      eDualkey.logAlt.meta.settings.errorMode,
      { expectedFinalText: expected },
    );
    expect(replay.finalText).toBe(expected);
    expect(replay.corrupted).toBe(false);
  });
});
